"""migration

Revision ID: 6a2153b0c975
Revises:
Create Date: 2026-09-22 13:23:18.673362

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6a2153b0c975"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("GOOGLE", name="provider_enum").create(op.get_bind())
    sa.Enum("USER", "ADMIN", name="role_enum").create(op.get_bind())
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=False,
            comment="Уникальный адрес электронной почты пользователя",
        ),
        sa.Column(
            "password_hash",
            sa.String(length=255),
            nullable=True,
            comment="Хеш пароля (может отсутствовать при входе через OAuth)",
        ),
        sa.Column(
            "nickname",
            sa.String(length=25),
            nullable=False,
            comment="Публичный никнейм пользователя",
        ),
        sa.Column(
            "role",
            postgresql.ENUM("USER", "ADMIN", name="role_enum", create_type=False),
            server_default="USER",
            nullable=False,
            comment="Роль пользователя в системе для разграничения прав доступа",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="Флаг активности учетной записи",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Флаг мягкого удаления (soft delete)",
        ),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Временная метка soft delete",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "nickname ~ '^[a-zA-Z0-9_ .-]+$'", name="check_nickname_format"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("nickname"),
        comment="Таблица учетных записей пользователей",
    )
    op.create_table(
        "user_providers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "user_id",
            sa.Uuid(),
            nullable=False,
            comment="Идентификатор пользователя-владельца провайдера",
        ),
        sa.Column(
            "provider",
            postgresql.ENUM("GOOGLE", name="provider_enum", create_type=False),
            nullable=False,
            comment="Тип внешнего OAuth-провайдера аутентификации",
        ),
        sa.Column(
            "provider_id",
            sa.String(length=255),
            nullable=False,
            comment="Уникальный идентификатор пользователя внутри сервиса провайдера",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", "user_id"),
        sa.UniqueConstraint(
            "provider", "provider_id", name="uq_user_providers_provider_provider_id"
        ),
        comment="Связи аккаунтов пользователей с внешними OAuth-провайдерами",
    )
    op.create_index(
        "ix_user_providers_user_id", "user_providers", ["user_id"], unique=False
    )
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "user_id",
            sa.Uuid(),
            nullable=False,
            comment="Идентификатор пользователя, которому принадлежит сессия",
        ),
        sa.Column(
            "refresh_token_jti",
            sa.String(length=255),
            nullable=False,
            comment="Уникальный JWT ID (JTI) refresh-токена",
        ),
        sa.Column(
            "user_agent",
            sa.String(length=512),
            nullable=True,
            comment="User-Agent клиентского устройства",
        ),
        sa.Column(
            "ip_address",
            sa.String(length=45),
            nullable=True,
            comment="IP-адрес клиента (IPv4 или IPv6)",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Временная метка истечения срока действия сессии",
        ),
        sa.Column(
            "is_revoked",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Флаг принудительного отзыва сессии",
        ),
        sa.Column(
            "revoked_reason",
            sa.String(length=512),
            nullable=True,
            comment="Причина отзыва сессии",
        ),
        sa.Column(
            "revoked_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Временная метка отзыва сессии",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", "user_id"),
        sa.UniqueConstraint("refresh_token_jti"),
        comment="Активные и архивные сессии пользователей (Refresh токены)",
    )
    op.create_index(
        "ix_user_sessions_expires_at", "user_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        "ix_user_sessions_user_id", "user_sessions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_sessions_user_id", table_name="user_sessions")
    op.drop_index("ix_user_sessions_expires_at", table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index("ix_user_providers_user_id", table_name="user_providers")
    op.drop_table("user_providers")
    op.drop_table("users")
    sa.Enum("USER", "ADMIN", name="role_enum").drop(op.get_bind())
    sa.Enum("GOOGLE", name="provider_enum").drop(op.get_bind())
    # ### end Alembic commands ###
